name: Generator Po-token
on:
  workflow_dispatch:
jobs:
  Generator_Po_token:
    name: Generator Po-token
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.12.0"
      - name: Install
        run: npm install youtube-po-token-generator
      - name: Run
        run: |
          echo -e '#!/usr/bin/env node\n\nconst { generate } = require("youtube-po-token-generator")\n\ngenerate().then(console.log, console.error)' > ./get-potoken.js
          chmod +x get-potoken.js
          ./get-potoken.js
